version: "3"
services:
    redis-server:
        image: "redis"
    node-app:
        # "no", always, on-failure, unless-stopped
        restart: always
        build: .
        ports:
            - "4001:8081"
